### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by uppaljs** [Kavan/BSSAuto#1]
Is this a CRM extension to Redknee's BSS platform?

**Comment by Kavan** [comment]
It is just a basic framework to test Redknee's BSS platform.
Which I am developing to reduce my day to day work.
nothing specific to Redknee BSS  (except Page Objects), it just a sample  web application.

**Comment by uppaljs** [comment]
@Kavan - Apologies for the delayed response , I have pretty extensive experience on BSS platforms ( Redknee / Ericsson / Huawei )  and am very interested in this , I hope I'll be able to contribute to this.
